### ISSUE TITLE
Running Zonation 5 from the linux terminal as before

### ISSUE THREAD

**Issue by 8Ginette8** [zonationteam/Zonation5#4]
Hi there,

Being quick a frequent user of Zonation 4 I love the program and its features. I was not having Linux installed but rather using a singularity container on a HPC cluster (with a non-GUI Linux installed) with zonation 4 installed (following https://github.com/cbig/zonation-core). Unfortunately I cannot now figure out how to do the same with Zonation 5. I don't want to use the GUI version but rather run the z5 command line directly from the terminal. But since now (not like the link above) there is only an Appimage available, I cannot get my head around on how to use it to run z5 from the terminal. Some help or tutorial would be much appreciated! Thank you for your help :).

Yohann

**Comment by kirahvi** [comment]
Hi

The appimage can be run with or without GUI.
So for instance, if you have the zonation5 appimage in your current directory, you can just run it like this:

./zonation5 your_project.z5 your_output_dir

That will run the project without GUI. Run ./zonation5 --help, to get a list of the command line options, and see the manual for longer descriptions.

It may not work in some older Linux distributions, in which case you will get an error about the GLIBC version.

**Comment by 8Ginette8** [comment]
Great I will try, thanks!

**Comment by ysagon** [comment]
I'm facing exactly what @kirahvi said: GLIBC too old (Rocky8). Are there any option such as using a container?
