### ISSUE TITLE
Zonation 5 does not run ... 

### ISSUE THREAD

**Issue by dpoursanidis** [zonationteam/Zonation5#7]
Dear team

Following the instructions at the [tutorial](https://sustainability-gis.readthedocs.io/en/latest/lessons/L6/zonation-tutorial.html#tutorial-instructions), is impossible to repeat the analysis.

I have change the path for the e.xe in the z5_call.cmd file (see here > 
[z5_call.zip](https://github.com/zonationteam/Zonation5/files/14547100/z5_call.zip) and when double click, nothing happens.

Practically, something goes to open (like a cmd window with white letters) but is fast enough to see what is going on. And no GUI appear, nor out folder is created.

The path of the tutorial data is under > C:\Users\dpour\Desktop\Zonations5_Tutorial and no changes at the structure of the folder have been made:

![image](https://github.com/zonationteam/Zonation5/assets/8640644/095cf4df-92d9-4679-9d2e-e3644cb3e50d)

Any idea on what might cause that?

Thansk in advance

**Comment by kirahvi** [comment]
You can see if there's some error message in the command prompt window by adding a line at the end of your z5_call.cmd file, with the text: `@pause`, which will make the window remain open.

**Comment by dpoursanidis** [comment]
Thanks for the hind.

Here is the result

![image](https://github.com/zonationteam/Zonation5/assets/8640644/66906715-1f7e-4611-a3b8-c059358f3e18)

**Comment by kirahvi** [comment]
Looks like the tutorial at https://sustainability-gis.readthedocs.io/en/latest/lessons/L6/zonation-tutorial.html#tutorial-instructions contains some outdated information. The course was made before the first version of Zonation 5 was officially released, and  some details in the software changed before the release. 

In this case, the -a0 option doesn't work, the area number must be given to the --area option, as explained in the usage text of the command. So the command would be: `z5 --gui --mode=ABF -a --area=0 01_abf_hab.z5 out`

**Comment by dpoursanidis** [comment]
Fixed following your guidelines!!

![image](https://github.com/zonationteam/Zonation5/assets/8640644/607cb41e-3be0-426d-89f8-8f02dd39b654)


Are plans for the tutorial and the relevant data to be updated since all .z5 files have the same issue?

**Comment by dpoursanidis** [comment]
While the test data are now running, at least for the ABF, i try to change the input features with a personal dataset. I change the paths to my species data and in the console i recieve the following errors

[2024-03-14 16:12:24.399] [info] Loading feature layer information from "D:\Zonations\exercise-6-dpoursanidis-master\01_abf_hab\features.txt"
[2024-03-14 16:12:24.407] [error] No such file: "../data/01_biodiversity_features/03_Angelsharks/forest/Squatina_squatina_cloglog.tif" in "D:\Zonations\exercise-6-dpoursanidis-master\01_abf_hab\features.txt" line 2
[2024-03-14 16:12:24.414] [error] No such file: "../data/01_biodiversity_features/03_Angelsharks/forest/Squatina_oculata_cloglog.tif" in "D:\Zonations\exercise-6-dpoursanidis-master\01_abf_hab\features.txt" line 3
[2024-03-14 16:12:24.430] [error] No such file: "../data/01_biodiversity_features/03_Angelsharks/forest/Squatina_sp_cloglog.tif" in "D:\Zonations\exercise-6-dpoursanidis-master\01_abf_hab\features.txt" line 4
[2024-03-14 16:12:24.434] [error] Errors while loading project

But the list points to the correct path

[features.txt](https://github.com/zonationteam/Zonation5/files/14603518/features.txt)

D:\Zonations\exercise-6-dpoursanidis-master\data\01_biodiversity_features\03_Angelsharks 

![image](https://github.com/zonationteam/Zonation5/assets/8640644/2bdfb8b4-7a47-4ef5-947f-7282e0307924)


What am doing wrong here?

**Comment by kirahvi** [comment]
That course is not made by us, but the page has been now updated to include a warning that it doesn't apply to the current version of the software.
